services:
  kluisz:
    image: kluisz/kluisz-ai-canvas:latest # or another version tag on https://hub.docker.com/r/kluisz/kluisz-ai-canvas
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - KLUISZ_DATABASE_URL=postgresql://kluisz:kluisz@postgres:5432/kluisz
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - KLUISZ_CONFIG_DIR=/app/kluisz
    volumes:
      - kluisz-data:/app/kluisz

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: kluisz
      POSTGRES_PASSWORD: kluisz
      POSTGRES_DB: kluisz
    ports:
      - "5432:5432"
    volumes:
      - kluisz-postgres:/var/lib/postgresql/data

volumes:
  kluisz-postgres:
  kluisz-data:
