apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kluisz-ai-canvas.fullname" . }}-config
  labels:
    {{- include "kluisz-ai-canvas.labels" . | nindent 4 }}
data:
  config-dir: {{ .Values.kluisz.env.configDir | quote }}
